CREATE TABLE dados_ficha_a_desafio (
    id_paciente UUID PRIMARY KEY,
    sexo VARCHAR(6),
    obito BOOLEAN,
    bairro VARCHAR(255),
    raca_cor VARCHAR(20),
    ocupacao VARCHAR(255),
    religiao VARCHAR(255),
    luz_eletrica BOOLEAN,
    data_cadastro TIMESTAMP,
    escolaridade VARCHAR(100),
    nacionalidade VARCHAR(100),
    renda_familiar VARCHAR(50),
    data_nascimento DATE,
    em_situacao_de_rua BOOLEAN,
    frequenta_escola BOOLEAN,
    meios_transporte JSONB,
    doencas_condicoes JSONB,
    identidade_genero VARCHAR(50),
    meios_comunicacao JSONB,
    orientacao_sexual VARCHAR(50),
    possui_plano_saude BOOLEAN,
    em_caso_doenca_procura JSONB,
    situacao_profissional VARCHAR(100),
    vulnerabilidade_social BOOLEAN,
    data_atualizacao_cadastro TIMESTAMP,
    familia_beneficiaria_auxilio_brasil BOOLEAN,
    crianca_matriculada_creche_pre_escola BOOLEAN,
    altura DECIMAL(5,2),
    peso DECIMAL(5,2),
    pressao_sistolica DECIMAL(5,2),
    pressao_diastolica DECIMAL(5,2),
    n_atendimentos_atencao_primaria INT,
    n_atendimentos_hospital INT,
    updated_at TIMESTAMP,
    tipo VARCHAR(25)
);

-- tabela de dados brutos importada com o comando \copy no psql